[package]
name = "komodo-passphrase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
secp256k1 = "0.20.3"
hex = "0.4.3"
bitcoin_hashes = "0.10.0"
base58 = "0.2.0"
